server:
  port: 8085
  error:
    include-message: always

spring:
  kafka:
    bootstrap-servers: ${KAFKA_HOST:kafka:9092}
    producer:
     value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
     properties:
      spring:
       json:
        add:
         type:
          headers: false
