version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  db:
    image: mariadb:latest
    environment:
      MARIADB_USER: maria
      MARIADB_PASSWORD: maria
      MARIADB_ROOT_PASSWORD: maria-root
      MARIADB_DATABASE: microservices

  microservice-websocket:
    image: microservice-websocket-test
    container_name: websocket-app
    ports:
      - "8085:8085"
    environment:
      KAFKA_HOST: kafka:9092
    depends_on:
      - kafka

  microservice-kafka:
    image: microservice-kafka-test
    container_name: microservice-kafka
    ports:
      - "8088:8088"
    environment:
      KAFKA_HOST: kafka:9092
      MARIA_HOST: http://microservice-maria:8082
    depends_on:
      - kafka

  microservice-maria:
    image: microservices-mariadb-test
    container_name: microservice-maria
    environment:
      DATABASE_URL: mariadb://db:3306/microservices
    depends_on:
      - db
    ports:
      - "8082:8082"